version: '3.9'
services:
  flask_app:
    container_name: api_carreras
    image: adan441/api_flask_live:1.0.0
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgres:password@flask_db:5432/ITL
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ITL
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}